version: '3'

services:
   db:
     container_name: smartimport-db-container
     image: mariadb:latest
     restart: always
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: cve4Zwdh5AaxNxUk
       MYSQL_DATABASE: smartimport-db
       MYSQL_USER: smartsite
       MYSQL_PASSWORD: cve4Zwdh5AaxNxUk

   wordpress:
     depends_on:
       - db
     container_name: smartimport-wp-container
     image: wordpress:latest
     restart: always
     ports:
       - "80:80"
     volumes:
       - ${WP_CORE}:/var/www/html
       - ${WP_CONTENT}:/var/www/html/wp-content
       - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
       - ./conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     environment:
       WORDPRESS_DB_HOST: smartimport-db-container:3306
       WORDPRESS_DB_NAME: smartimport-db
       WORDPRESS_DB_USER: smartsite
       WORDPRESS_DB_PASSWORD: cve4Zwdh5AaxNxUk
       WORDPRESS_TABLE_PREFIX: wp_
#       VIRTUAL_HOST: smart-import.com,www.smart-import.com
#       LETSENCRYPT_HOST: smart-import.com,www.smart-import.com
#       LETSENCRYPT_EMAIL: hilderalbertohm@gmail.com
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    external_links:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: cve4Zwdh5AaxNxUk
#networks:
#    default:
#       external:
#         name: ${NETWORK}
